# ref: https://github.com/actions/runner-images
name: amd64 Linux CMake

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python: [
          {version: '3.9'},
          {version: '3.10'},
          {version: '3.11'},
          {version: '3.12'},
          #{version: '3.13'},
        ]
        cmake: [
          {generator: "Unix Makefiles", config: "Release"},
          {generator: "Ninja", config: "Release"},
          #{generator: "Ninja Multi-Config", config: "Release"},
        ]
      fail-fast: false
    name: Linux•CMake(${{ matrix.cmake.generator }})•Python${{ matrix.python.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Check Python
        run: |
          python --version
          python -m platform
      - name: Install Python requirements
        run: python -m pip install --upgrade -r $(python -c 'import sys; print("./pybind11_protobuf/requirements/requirements_lock_%d_%d.txt" % (sys.version_info[:2]))')
      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Check CMake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "${{ matrix.cmake.generator }}"
          -DCMAKE_BUILD_TYPE=${{ matrix.cmake.config }}
          -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target all
          -v -j2
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target test
          -v
      - name: Install
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target install
          -v

  amd64_linux_cmake:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v4
